build_stage:
    stage: build
    script:
        - '# Build the store-connector'
        - chmod +x .gitlab-ci/build.sh
        - .gitlab-ci/build.sh --dev
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /\/ninja\/stage/

metrics_stage:
    stage: run
    when: on_success
    artifacts:
        name: "$CI_COMMIT_SHA-metrics"
        paths:
            - docs/metrics
        expire_in: 1 week
    script:
        - '# Metrics store-connector.'
        - chmod +x .gitlab-ci/metrics.sh
        - .gitlab-ci/metrics.sh
    only:
        variables:
            - $CI_COMMIT_MESSAGE =~ /\/ninja\/stage.*\/metrics/
