version: "3.1"
services:
    server:
        build: ./server
        image: shop/php-{{phpVersion}}:v1
        container_name: store-connector-server-{{branch}}-{{phpVersion}}
        ports:
            - "{{serverPort}}:80"
        volumes:
            - ./shop/src:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        environment:
            - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    mysql:
        image: mysql:5.7
        container_name: store-connector-mysql-{{branch}}
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=gxdev
            - MYSQL_USER=gxdev
            - MYSQL_PASSWORD=gxdev
            - DOCKER_HOST_IP=${DOCKER_HOST_IP}
        ports:
            - "{{mysqlPort}}:3306"
